<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="Homepage.css">
    
    <title>Home Page</title>
</head>
<body>
    <div id="Wrapper">
        <div id="Slideshow">
            <img src = "" id="slide" width="500" height="500">
            <button onclick="leftBtn();"></button>
            <button onclick="rightBtn();"></button>
        </div>
        <div class ="SideImg">
            <img src="HomepagePics/SideAD_1.png" class ="SideImg">
            <img src="HomepagePics/SideAD_2.png" class ="SideImg">
            <img src="HomepagePics/SideAD_3.png" class ="SideImg">
        </div>
    </div>
    <script src="SlideShow.Js"></script>
    <span></span>

</body>
</html>
